# Generated by Django 3.1.2 on 2020-12-10 14:32

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import investment_guide.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_created', models.DateTimeField(auto_created=True)),
                ('account_number', models.IntegerField(default=investment_guide.models.account_number_generator, max_length=10)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('commission_type', models.CharField(default='revshare', max_length=200)),
                ('commission_fixed_per_lot', models.IntegerField()),
                ('commission_revshare', models.IntegerField()),
                ('is_trial_period_enabled', models.BooleanField(default=False)),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255)),
                ('experience', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('country_code', models.CharField(max_length=5)),
                ('gain', models.DecimalField(decimal_places=2, max_digits=19)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('loss', models.DecimalField(decimal_places=2, max_digits=19)),
                ('copiers_count', models.IntegerField()),
                ('copiers_delta', models.IntegerField()),
                ('time_with_us_days', models.IntegerField()),
                ('is_subscribed', models.BooleanField(default=False)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=19)),
                ('strategy_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Traders',
                'verbose_name_plural': 'Traders',
            },
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('sell', 'sell'), ('buy', 'buy')], max_length=15)),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('open_time', models.TimeField(auto_now_add=True)),
                ('close_time', models.TimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=19)),
                ('symbol', models.CharField(max_length=8)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('is_trade', models.BooleanField(default=True)),
                ('currency', models.CharField(default='BTC', max_length=10)),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment_guide.trader')),
            ],
            options={
                'verbose_name': 'Trade History',
                'verbose_name_plural': 'Trade Histories',
            },
        ),
    ]
