# Generated by Django 3.1.2 on 2020-12-14 22:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_guide', '0002_auto_20201210_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='trader'),
        ),
    ]
