# Generated by Django 3.1.2 on 2020-12-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_guide', '0005_auto_20201223_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='close_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
