# Generated by Django 3.1.2 on 2020-12-23 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_guide', '0006_auto_20201223_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='close_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 12, 23, 23, 30, 3, 418713), null=True),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.datetime(2020, 12, 23, 23, 40, 3, 418766), null=True),
        ),
    ]
