# Generated by Django 3.1.2 on 2020-12-23 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_guide', '0007_auto_20201223_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='close_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 12, 24, 0, 2, 7, 959115), null=True),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
