# Generated by Django 3.1.2 on 2021-01-01 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_guide', '0011_auto_20201224_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='socials',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='close_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 1, 1, 47, 20, 374973), null=True),
        ),
    ]
