# Generated by Django 3.1.2 on 2021-01-01 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_guide', '0012_auto_20210101_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='close_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 1, 2, 17, 1, 103437), null=True),
        ),
    ]
