# Generated by Django 3.1.2 on 2021-01-01 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_guide', '0014_auto_20210101_0213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='close_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 1, 13, 23, 9, 975247), null=True),
        ),
    ]
