# Generated by Django 3.1.2 on 2021-01-23 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_guide', '0017_auto_20210104_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='close_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 23, 14, 29, 45, 524141), null=True),
        ),
    ]
