# Generated by Django 3.1.2 on 2021-05-02 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_guide', '0018_auto_20210123_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='close_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 5, 2, 23, 6, 56, 434718), null=True),
        ),
    ]
