# Generated by Django 3.1.2 on 2021-07-11 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_guide', '0019_auto_20210502_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='close_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 7, 11, 16, 21, 33, 746255), null=True),
        ),
    ]
