# Generated by Django 3.1.2 on 2021-07-12 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_guide', '0020_auto_20210711_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='close_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 7, 12, 22, 26, 6, 218402), null=True),
        ),
    ]
