# Generated by Django 3.1.2 on 2021-09-07 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_guide', '0021_auto_20210712_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='close_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 9, 7, 20, 39, 44, 462120), null=True),
        ),
    ]
