# Generated by Django 3.1.2 on 2021-09-07 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_guide', '0023_auto_20210907_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='close_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 9, 7, 21, 39, 13, 459713), null=True),
        ),
    ]
