# Generated by Django 3.1.1 on 2020-09-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200929_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useramount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=19),
        ),
    ]
