# Generated by Django 3.1 on 2020-08-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('referral_code', models.CharField(blank=True, max_length=250)),
                ('full_name', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Sign Up',
                'verbose_name_plural': 'User Sign Up',
            },
        ),
        migrations.CreateModel(
            name='RecentTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.CharField(max_length=60)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('tokens', models.DecimalField(decimal_places=2, max_digits=9)),
                ('details', models.CharField(choices=[('Deposit to wallet', 'Deposit to wallet'), ('Withdrawal from wallet', 'Withdrawal from wallet')], max_length=100)),
            ],
            options={
                'verbose_name': 'Recent Transactions',
                'verbose_name_plural': 'Recent Transactions',
            },
        ),
    ]
