# Generated by Django 3.1.1 on 2020-09-17 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertransaction',
            old_name='type_of_transaction',
            new_name='transaction_type',
        ),
    ]
