# Generated by Django 3.1 on 2020-09-02 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apex_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type_of_transaction', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount_in_btc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.CharField(choices=[('Deposit to wallet', 'Deposit to wallet'), ('Withdrawal from wallet', 'Withdrawal from wallet')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Transactions',
                'verbose_name_plural': 'User Transactions',
            },
        ),
    ]
