# Generated by Django 3.1 on 2020-08-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
    ]
