# Generated by Django 3.1.1 on 2020-09-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex_api', '0002_auto_20200917_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
