# Generated by Django 3.1.1 on 2020-09-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex_api', '0003_usertransaction_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReferralLink',
        ),
    ]
