# Generated by Django 3.1.1 on 2020-09-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex_api', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='fdhdfs.jpg', upload_to='profile_pics'),
        ),
    ]
