# Generated by Django 3.1.2 on 2020-10-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex_api', '0003_auto_20201011_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='amount_in_btc',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
