# Generated by Django 3.1.2 on 2020-11-06 13:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex_api', '0004_auto_20201011_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='fdhdfs.jpg', max_length=255, verbose_name='profile_pics'),
        ),
    ]
