# Generated by Django 3.1.1 on 2020-09-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex_api', '0004_delete_userreferrallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='user_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
