# Generated by Django 3.1.2 on 2021-01-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex_api', '0005_auto_20201106_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='investor',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
