# Generated by Django 3.1.1 on 2020-09-26 19:03

import apex_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex_api', '0005_usertransaction_user_bal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='user_bal',
            field=models.DecimalField(decimal_places=2, default=apex_api.models.UserTransaction.user_balance, max_digits=10),
        ),
    ]
