# Generated by Django 3.1.1 on 2020-09-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex_api', '0006_auto_20200926_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransaction',
            name='user_bal',
        ),
    ]
