# Generated by Django 3.1.2 on 2021-01-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex_api', '0006_user_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_linked',
            field=models.BooleanField(default=False),
        ),
    ]
