# Generated by Django 3.1.1 on 2020-09-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex_api', '0007_remove_usertransaction_user_bal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='amount_in_btc',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
